use crate::error::AppError;
use std::fmt::{self, Display};
use std::path::Path;

/// Standard OpenSSH identity filenames that also match the managed-key grammar.
const RESERVED_KEY_NAMES: [&str; 3] = ["id_ecdsa_sk", "id_ed25519_sk", "id_mldsa44_ed25519"];

/// The single grammar for ssv-managed key filenames: `id_<key_type>_<host>`.
///
/// This is the sole authority for producing and recognizing managed key names. `render`/
/// `identity_directive` produce the on-disk filename and the `IdentityFile` directive value;
/// `parse` recognizes a filename; `new` constructs a name for generation, rejecting collisions
/// with reserved OpenSSH names.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ManagedKeyName {
    key_type: String,
    host: HostIdentifier,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum KeyFileKind {
    Private,
    Public,
}

impl ManagedKeyName {
    pub(crate) fn new(key_type: &str, host: HostIdentifier) -> Result<Self, AppError> {
        validate_key_type(key_type)?;
        let name = Self { key_type: key_type.to_string(), host };
        if RESERVED_KEY_NAMES.contains(&name.render().as_str()) {
            return Err(AppError::validation(format!(
                "refusing to generate key '{}': it collides with a reserved OpenSSH key name",
                name.render()
            )));
        }
        Ok(name)
    }

    /// Recognize a private-key filename as a managed key name. Returns `None` for reserved
    /// OpenSSH names, non-managed grammar, or invalid key type/host.
    pub(crate) fn parse(filename: &str) -> Option<Self> {
        if RESERVED_KEY_NAMES.contains(&filename) {
            return None;
        }
        let (key_type, host) = filename.strip_prefix("id_")?.split_once('_')?;
        if validate_key_type(key_type).is_err() || HostIdentifier::new(host).is_err() {
            return None;
        }
        Some(Self { key_type: key_type.to_string(), host: HostIdentifier(host.to_string()) })
    }

    pub(crate) fn parse_file(filename: &str) -> Option<(Self, KeyFileKind)> {
        if let Some(private) = filename.strip_suffix(".pub") {
            Self::parse(private).map(|name| (name, KeyFileKind::Public))
        } else {
            Self::parse(filename).map(|name| (name, KeyFileKind::Private))
        }
    }

    pub(crate) fn key_type(&self) -> &str {
        &self.key_type
    }

    pub(crate) fn host(&self) -> &HostIdentifier {
        &self.host
    }

    /// The key-pair filename, e.g. `id_ed25519_github.com`.
    pub(crate) fn render(&self) -> String {
        format!("id_{}_{}", self.key_type, self.host.as_str())
    }

    /// The `IdentityFile` directive value, e.g. `~/.ssh/id_ed25519_github.com`.
    pub(crate) fn identity_directive(&self) -> String {
        format!("~/.ssh/{}", self.render())
    }
}

/// Return the key type of a managed identity path that belongs to `host`, or an error if the
/// filename is not an ssv-owned managed key for that host.
pub(crate) fn managed_key_type(path: &Path, host: &HostIdentifier) -> Result<String, AppError> {
    let filename = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| AppError::validation("IdentityFile has no UTF-8 filename"))?;
    if RESERVED_KEY_NAMES.contains(&filename) {
        return Err(reserved_identity(path, host));
    }
    match ManagedKeyName::parse(filename) {
        Some(name) if name.host() == host => Ok(name.key_type().to_string()),
        _ => Err(unmanaged_identity(path, host)),
    }
}

fn unmanaged_identity(path: &Path, host: &HostIdentifier) -> AppError {
    AppError::managed_identity(format!(
        "refusing to manage identity '{}' because it does not match host '{host}'",
        path.display()
    ))
}

/// A managed config references a reserved OpenSSH key name (e.g. a host literally named `sk`
/// generated by an older ssv). ssv cannot manage or delete it, because the filename is
/// indistinguishable from a personal OpenSSH key. Explain the situation and give manual recovery.
fn reserved_identity(path: &Path, host: &HostIdentifier) -> AppError {
    let removal = match path.parent() {
        Some(root) => {
            let conf = root.join("conf.d").join(format!("{host}.conf"));
            format!("rm {} {}.pub {}", path.display(), path.display(), conf.display())
        }
        None => format!("rm {} {}.pub", path.display(), path.display()),
    };
    AppError::managed_identity(format!(
        "identity '{}' is a reserved OpenSSH key name; ssv does not manage it (it is \
         indistinguishable from a personal OpenSSH key). If an older ssv created host '{host}', \
         remove it manually: {removal}",
        path.display()
    ))
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub(crate) struct HostIdentifier(String);

impl HostIdentifier {
    pub(crate) fn new(host: &str) -> Result<Self, AppError> {
        if host.is_empty() {
            return Err(AppError::validation("host must not be empty"));
        }
        if host.starts_with('-')
            || !host.chars().all(|character| {
                character.is_ascii_alphanumeric() || matches!(character, '.' | '-' | '_')
            })
        {
            return Err(AppError::validation(format!(
                "invalid host identifier '{host}'; expected alphanumeric, '.', '-', or '_' characters without a leading '-'"
            )));
        }
        Ok(Self(host.to_string()))
    }

    pub(crate) fn as_str(&self) -> &str {
        &self.0
    }
}

impl Display for HostIdentifier {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

pub(crate) fn validate_key_type(key_type: &str) -> Result<(), AppError> {
    if key_type.is_empty()
        || key_type.starts_with('-')
        || !key_type.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
    {
        return Err(AppError::validation(format!(
            "invalid key type '{key_type}'; expected ASCII alphanumeric or '-' characters without a leading '-'"
        )));
    }
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Hostname(String);

impl Hostname {
    pub(crate) fn new(hostname: &str) -> Result<Self, AppError> {
        if hostname.is_empty() {
            return Err(AppError::validation("hostname must not be empty"));
        }
        let allowed = |character: char| {
            character.is_ascii_alphanumeric()
                || matches!(character, '.' | '-' | '_' | '[' | ']' | ':')
        };
        if hostname.starts_with('-') || !hostname.chars().all(allowed) {
            return Err(AppError::validation(format!(
                "invalid hostname '{hostname}'; expected alphanumeric, '.', '-', '_', '[', ']', or ':' characters without a leading '-'"
            )));
        }
        Ok(Self(hostname.to_string()))
    }

    pub(crate) fn as_str(&self) -> &str {
        &self.0
    }
}

impl Display for Hostname {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct RemoteUser(String);

impl RemoteUser {
    pub(crate) fn new(user: &str) -> Result<Self, AppError> {
        if user.is_empty() {
            return Err(AppError::validation("user must not be empty"));
        }
        if user.starts_with('-')
            || user.contains('@')
            || user.chars().any(|character| character.is_control() || character.is_whitespace())
        {
            return Err(AppError::validation(
                "invalid user; whitespace, control characters, '@', and a leading '-' are not allowed",
            ));
        }
        Ok(Self(user.to_string()))
    }

    pub(crate) fn as_str(&self) -> &str {
        &self.0
    }
}

impl Display for RemoteUser {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_and_directive_round_trip() {
        let name = ManagedKeyName::new("ed25519", HostIdentifier::new("github.com").expect("host"))
            .expect("valid name");
        assert_eq!(name.render(), "id_ed25519_github.com");
        assert_eq!(name.identity_directive(), "~/.ssh/id_ed25519_github.com");

        let parsed = ManagedKeyName::parse(&name.render()).expect("round-trip parse");
        assert_eq!(parsed.key_type(), "ed25519");
        assert_eq!(parsed.host().as_str(), "github.com");
    }

    #[test]
    fn host_with_underscore_round_trips() {
        let name = ManagedKeyName::new("ed25519", HostIdentifier::new("foo_bar").expect("host"))
            .expect("valid name");
        assert_eq!(name.render(), "id_ed25519_foo_bar");
        let parsed = ManagedKeyName::parse("id_ed25519_foo_bar").expect("parse");
        assert_eq!(parsed.key_type(), "ed25519");
        assert_eq!(parsed.host().as_str(), "foo_bar");
    }

    #[test]
    fn reserved_names_are_rejected_only_when_they_collide() {
        let sk = HostIdentifier::new("sk").expect("host");
        assert!(ManagedKeyName::new("ed25519", sk.clone()).is_err());
        assert!(ManagedKeyName::new("ecdsa", sk.clone()).is_err());
        assert_eq!(ManagedKeyName::new("rsa", sk).expect("valid").render(), "id_rsa_sk");
        assert!(
            ManagedKeyName::new("mldsa44", HostIdentifier::new("ed25519").expect("host")).is_err()
        );
        assert_eq!(
            ManagedKeyName::new("ed25519", HostIdentifier::new("foo_sk").expect("host"))
                .expect("valid")
                .render(),
            "id_ed25519_foo_sk"
        );
    }

    #[test]
    fn parse_ignores_reserved_and_non_managed_names() {
        assert!(ManagedKeyName::parse("id_ed25519_sk").is_none());
        assert!(ManagedKeyName::parse("id_ecdsa_sk").is_none());
        assert!(ManagedKeyName::parse("id_mldsa44_ed25519").is_none());
        assert!(ManagedKeyName::parse("id_ed25519").is_none());
        assert!(ManagedKeyName::parse("random").is_none());
    }

    #[test]
    fn parse_recognizes_legitimate_sk_suffixed_host() {
        // A `*_sk` host is ssv-owned and must be recognizable so audit can flag it as orphaned.
        let parsed = ManagedKeyName::parse("id_ed25519_deploy_sk").expect("parse");
        assert_eq!(parsed.host().as_str(), "deploy_sk");
    }

    #[test]
    fn managed_key_type_reports_reserved_name_with_recovery() {
        // A legacy host named `sk` (created by an older ssv) surfaces an explicit, actionable
        // error rather than the generic "does not match host" message.
        let host = HostIdentifier::new("sk").expect("host");
        let err = managed_key_type(Path::new("/home/u/.ssh/id_ed25519_sk"), &host).unwrap_err();
        let message = err.to_string();
        assert!(message.contains("reserved OpenSSH key name"));
        assert!(message.contains("remove it manually"));
        assert!(message.contains("/home/u/.ssh/conf.d/sk.conf"));
    }

    #[test]
    fn host_validation_accepts_managed_identifiers() {
        assert!(HostIdentifier::new("github.com").is_ok());
        assert!(HostIdentifier::new("internal-host_01").is_ok());
    }

    #[test]
    fn host_validation_rejects_path_components() {
        assert!(HostIdentifier::new("bad/host").is_err());
        assert!(HostIdentifier::new("spaces host").is_err());
        assert!(HostIdentifier::new("-option").is_err());
    }

    #[test]
    fn managed_key_files_include_public_keys_and_exclude_standard_keys() {
        assert!(ManagedKeyName::parse_file("id_ed25519").is_none());
        assert!(ManagedKeyName::parse_file("id_ed25519_sk").is_none());
        assert!(ManagedKeyName::parse_file("id_mldsa44_ed25519").is_none());
        assert!(ManagedKeyName::parse_file("id_mldsa44_ed25519.pub").is_none());
        assert_eq!(
            ManagedKeyName::parse_file("id_ed25519_github.com").map(|(_, kind)| kind),
            Some(KeyFileKind::Private)
        );
        assert_eq!(
            ManagedKeyName::parse_file("id_ed25519_github.com.pub").map(|(_, kind)| kind),
            Some(KeyFileKind::Public)
        );
    }

    #[test]
    fn key_type_validation_accepts_safe_tokens_and_rejects_filename_ambiguity() {
        assert!(validate_key_type("ed25519-sk").is_ok());
        assert!(validate_key_type("FUTURE-1").is_ok());
        assert!(validate_key_type("-option").is_err());
        assert!(validate_key_type("type_name").is_err());
        assert!(validate_key_type("type/name").is_err());
        assert!(validate_key_type("type name").is_err());
    }
}
